import cv2

from color import Color

IMAGE_WIDTH = 1280
IMAGE_HEIGHT = 720
IMAGE_SHAPE = (IMAGE_HEIGHT, IMAGE_WIDTH)
SKIP = 1
STATE_COOLDOWN = 1  # seconds
WINDOW_NAME = ''

# Fonts
SIZE_FONTS = 2
FONT_SCALE = 1
FONT_THICKNESS = 2
FONT = cv2.FONT_HERSHEY_SIMPLEX

# Figures
LINE_THICKNESS = 2

# Colors
BACKGROUND = Color.WHITE
FONT_COLOR = Color.BLACK
LEFT_COLOR = Color.RED
RIGHT_COLOR = Color.BLUE

# Geometry
DEG_IN_RAD = 0.017  # rad [0.017453292519 ^= 1°]

# Coordinates
INDEX_INDEX_LMS = 8
